# List of the api and their request


### test api call


###fetch all tickets
GET http://localhost:8000/api/v1

### add new tickets
POST http://localhost:8000/api/v1
Content-Type: application/json

{
    "task": "Playing games",
    "hr": 2
}

### delete tickets
DELETE http://localhost:8000/api/v1
Content-Type: application/json

{
    "id": "61297554e21d1a1ba419b5b5"
}

### update tickets
PATCH http://localhost:8000/api/v1
Content-Type: application/json

{
    "id": "61297a4ff0e9748ccd174c5f",
    "todo": false
}

